config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  root 'welcome#index'

  resources :current_users

  resources :user_cats, path: 'cats' do
    collection do
      get 'generate_name'
    end
  end

  authenticate :user do
    resources :missions, only: [:index] do
      member do
        post 'start', as: 'start'
      end
    end
    resources :trainings, only: [:index] do
      member do
        post 'start', as: 'start'
      end
    end
    resources :journeys, only: [:index] do
      collection do
        post 'start', as: 'start'
      end
    end
    resources :regenerations, only: [:index] do
      member do
        post 'start', as: 'start'
      end
    end
    resources :items, only: [:index] do
      collection do
        post 'eat', as: 'eat'
      end
    end
  end

end

app/models/cat_mission.rb
class CatMission < Delegator
  def initialize(cat:, mission:)
    @cat = cat
    @mission = mission
  end

  def __getobj__
    @mission
  end

  def __setobj__(obj)
    @mission = obj
  end
end

app/models/cat_training.rb
class CatTraining < Delegator
  def initialize(cat:, training:)
    @cat = cat
    @training = training
  end

  def cost
    @cat.send("attribute#{@training.attribute_id}")
  end

  def __getobj__
    @training
  end

  def __setobj__(obj)
    @training = obj
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  
end

app/models/journey.rb
class Journey
end

app/models/mission.rb
class Mission < ActiveYaml::Base
  set_root_path "#{Rails.root}/db/yaml"
  fields :name, :id, :required_attributes, :gold

  def awarded_gold
    rand(gold["from"].to_i..gold["to"].to_i)
  end
end

app/models/regeneration.rb
class Regeneration < ActiveYaml::Base
  set_root_path "#{Rails.root}/db/yaml"
  fields :name, :id
end

app/models/training.rb
class Training < ActiveYaml::Base
  set_root_path "#{Rails.root}/db/yaml"
  fields :name, :id, :attribute_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :name

  has_many :user_cats

  def email_required?
    false
  end

  def current_cat
    self.user_cats.first
  end
end

app/models/user_cat.rb
# Using UserCat name to avoid collisions

class UserCat < ActiveRecord::Base
  validates :name, presence: true, length: { in: 2..20 }

  belongs_to :user

  ACTION_COOLDOWN_IN_SECONDS = 15*60
  MAX_ENERGY = 100

  def interest(n)
    self.send("interest#{n}")
  end

  def attribute(n)
    self.send("attribute#{n}")
  end

  def busy?
    last_action_time = last_action_at || Date.new(2000,1,1)
    (Time.now.to_i - last_action_time.to_time.to_i) < ACTION_COOLDOWN_IN_SECONDS
  end

  def max_energy
    MAX_ENERGY
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :set_locale
  protect_from_forgery with: :exception

  def current_cat
    current_user.current_cat
  end

  private

  def set_locale
    # Locale detection turned off
    # 18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  layout "logged_in"

  def show
  end
end

app/controllers/current_users_controller.rb
class CurrentUsersController < ApplicationController
  layout false
  respond_to :json

  def show
    @data = { current_user: { id: 1, gold: current_user.gold, cat_energy: current_user.current_cat.energy } }
    render json: @data
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout "logged_in"

  def index
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  layout "logged_in"

  def index

  end
  def start

  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  layout false
  respond_to :json

  def index
    @missions = Mission.all
    @missions.map! do |mission|
      cat_mission = CatMission.new(cat: current_cat, mission: mission)
      ArchPresenter.present(cat_mission)
    end
  end

  def start
    response = StartMissionService.call(cat: current_cat, mission_id: params[:id], user: current_user)
    render json: response
  end
end

app/controllers/regenerations_controller.rb
class RegenerationsController < ApplicationController
  layout false
  respond_to :json

  def index
    @regenerations = Regeneration.all
    @regenerations.map! do |regeneration|
      ArchPresenter.present(regeneration)
    end
  end

  def start
    response = RegenerateCatEnergyService.call(cat: current_cat)
    render json: response
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  layout false
  respond_to :json

  def index
    @trainings = Training.all
    @trainings.map! do |training|
      cat_training = CatTraining.new(cat: current_cat, training: training)
      cat_training = ArchPresenter.present(cat_training)
    end
  end

  def start
    response = StartTrainingService.call(cat: current_cat, training_id: params[:id], user: current_user)
    render json: response
  end
end

app/controllers/user_cats_controller.rb
class UserCatsController < ApplicationController
  layout false
  before_action :authenticate_user!, except: [:generate_name]
  respond_to :json

  def show
    @cat = ArchPresenter.present(current_cat)
  end

  def generate_name
    cat_name = GenerateCatNameService.call
    render plain: cat_name
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      render template: "/welcome/static", layout: "logged_in"
    else
      @default_password = PasswordGenerator.generate
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_class(class_name)
    case class_name
    when 'notice'
      'alert-info'
    when 'alert'
      'alert-danger'
    when 'error'
      'alert-danger'
    else
      class_name
    end
  end

  def current_cat
    current_user.current_cat
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:div, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger alert-block">
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/cities/show.slim
| City

app/views/welcome/index.slim
= bootstrap_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
  h1 = t '.create_cat'
  #cat-create
    .cat-appearance
      img.setting-image-fur src="/public_images/appearance/fur/0.png"
      img.setting-image-eyes src="/public_images/appearance/eyes/0.png"
      img.setting-image-face src="/public_images/appearance/face/0.png"
    .settings
      .setting.setting-eyes
        button.btn.btn-default.btn-left type="button" &laquo;
        .name Eyes
        button.btn.btn-default.btn-right type="button" &raquo;
        .clearfix
        input.selected-eyes name="cat[eyes]" type="hidden" value="0"
      .setting.setting-fur
        button.btn.btn-default.btn-left type="button" &laquo;
        .name Fur
        button.btn.btn-default.btn-right type="button" &raquo;
        .clearfix
        input.selected-fur name="cat[fur]" type="hidden" value="0"
      .setting.setting-face
        button.btn.btn-default.btn-left type="button" &laquo;
        .name Face
        button.btn.btn-default.btn-right type="button" &raquo;
        .clearfix
        input.selected-face name="cat[face]" type="hidden" value="0"


  .row
    .col-sm-4.col-sm-offset-4.registration-form
      fieldset
        .form-group
          label = t '.cat_name'
          .input-group
            input.form-control type="text" value="Mr. Mittens" name="cat[name]" id="cat-name"
            span class="input-group-addon" id="cat-name-reload"
              span.glyphicon.glyphicon-refresh
        .form-group.text-center
          button#continue-button.btn.btn-lg.btn-success.button-cathead type="button"
            = t '.continue'
            |  &raquo;
      #hidden-fields
        = f.text_field :name, label: t('.your_login'), id: "registration-name"
      #hidden-password
        .col-xs-6
          input type="text" name="user[password]" value="#{@default_password}"
        .col-xs-6
          input type="text" name="user[password_confirmation]" value="#{@default_password}"
  #hidden-form-button.row
    .col-sm-4.col-sm-offset-4.text-center
      = f.submit(class: "btn btn-lg btn-primary", id: "button-create-cat", value: t('.create_cat'))